# Generated by Django 3.0 on 2020-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_rider',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(default=34567890, max_length=100),
            preserve_default=False,
        ),
    ]
